"""empty message

Revision ID: 432c725e327c
Revises: 
Create Date: 2023-09-11 14:18:35.247605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432c725e327c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
