"""initial

Revision ID: e141e1f55d26
Revises: 
Create Date: 2023-11-10 13:44:26.369539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e141e1f55d26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('area_code', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('google_id', sa.String(length=50), nullable=False),
    sa.Column('instagram', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=7), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('website', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
